### ISSUE TITLE
Update to Angular 14

### ISSUE THREAD

**Issue by Gamaroff** [werthdavid/ngx-kjua#61] opened 2022-09-04 16:38 UTC
Hi.

Thank you for the great plugin.

When running on Angular 14 the following error is displayed.

```
ERROR TypeError: (kjua_svg__WEBPACK_IMPORTED_MODULE_0___namespace_cache || kjua_svg__WEBPACK_IMPORTED_MODULE_0___namespace_cache) is not a function
    at get template [as template] (http://localhost/src_app_pages_receive_receive_module_ts.js:2464:206)
    at NgxKjuaComponent.renderCode (http://localhost/src_app_pages_receive_receive_module_ts.js:2469:23)
    at NgxKjuaComponent.updateView (http://localhost/src_app_pages_receive_receive_module_ts.js:2495:14)
    at NgxKjuaComponent.ngAfterViewInit (http://localhost/src_app_pages_receive_receive_module_ts.js:2
```

Using
```
"kjua-svg": "^1.13.1",
"ngx-kjua": "^1.14.4",
```

Is there an easy workaround?

Cheers.

**Comment by werthdavid** [comment] 2022-09-05 05:37
Not yet, sorry. Have to look into that and maybe get rid of ng-packagr as it seems that the problem is there..

**Comment by rbalet** [comment] 2022-09-09 11:56
@Gamaroff Should be online
@werthdavid  I think you shall close this issue

**Closed** 2022-09-09 11:56 UTC
